# Generated by Django 3.0.2 on 2020-01-28 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('arguments', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='argumentspost',
            name='content',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='argumentspost',
            name='title',
            field=models.TextField(default='hello'),
            preserve_default=False,
        ),
    ]
