# Generated by Django 3.0.2 on 2020-01-28 15:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('arguments', '0002_auto_20200128_1447'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ArgumentsPost',
            new_name='ArgumentPost',
        ),
    ]
