# Generated by Django 3.0.2 on 2020-01-28 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('arguments', '0003_auto_20200128_1555'),
    ]

    operations = [
        migrations.AddField(
            model_name='argumentpost',
            name='slug',
            field=models.SlugField(null=True),
        ),
    ]
