# Generated by Django 3.0.2 on 2020-02-04 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('arguments', '0004_argumentpost_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='argumentpost',
            name='title',
            field=models.CharField(max_length=120),
        ),
    ]
