# Generated by Django 3.0.2 on 2020-02-12 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('arguments', '0005_auto_20200212_0755'),
    ]

    operations = [
        migrations.AlterField(
            model_name='action',
            name='argument_id',
            field=models.CharField(max_length=120),
        ),
    ]
