# Generated by Django 3.0.2 on 2020-02-06 11:55

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('arguments', '0006_argumentpost_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='argumentpost',
            name='publish_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='argumentpost',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='argumentpost',
            name='updated',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
