# Generated by Django 3.0.2 on 2020-02-06 12:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('arguments', '0007_auto_20200206_1155'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='argumentpost',
            options={'ordering': ['-publish_date', '-updated', 'timestamp']},
        ),
    ]
