# Generated by Django 3.0.2 on 2020-02-12 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('arguments', '0007_auto_20200212_0820'),
    ]

    operations = [
        migrations.AddField(
            model_name='argumentpost',
            name='content',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='argumentpost',
            name='slug',
            field=models.SlugField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='argumentpost',
            name='title',
            field=models.CharField(default='chelsea', max_length=120),
            preserve_default=False,
        ),
    ]
