# Generated by Django 3.0.2 on 2020-02-12 09:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('arguments', '0008_auto_20200212_0824'),
    ]

    operations = [
        migrations.AddField(
            model_name='action',
            name='parent',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='arguments.ArgumentPost'),
        ),
    ]
