# Generated by Django 3.0.2 on 2020-02-06 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('arguments', '0008_auto_20200206_1208'),
    ]

    operations = [
        migrations.AddField(
            model_name='argumentpost',
            name='image',
            field=models.FileField(blank=True, null=True, upload_to='image/'),
        ),
    ]
