# Generated by Django 3.0.2 on 2020-03-03 20:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('arguments', '0010_remove_action_argument_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='argumentpost',
            name='tryit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='arguments.ArgumentPost'),
        ),
    ]
