# Generated by Django 3.0.2 on 2020-03-03 20:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('arguments', '0011_argumentpost_tryit'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='argumentpost',
            name='tryit',
        ),
    ]
