# Generated by Django 3.0.2 on 2020-03-03 20:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('arguments', '0012_remove_argumentpost_tryit'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='action',
            name='parent',
        ),
        migrations.AddField(
            model_name='argumentpost',
            name='parent',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='arguments.ArgumentPost'),
        ),
    ]
