# Generated by Django 3.0.2 on 2020-03-05 17:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('arguments', '0015_auto_20200305_1738'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': 'Categories'},
        ),
    ]
