# Generated by Django 3.0.2 on 2020-03-05 17:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('arguments', '0016_auto_20200305_1741'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': 'Categorie'},
        ),
    ]
