# Generated by Django 3.0.2 on 2020-03-06 18:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('arguments', '0018_auto_20200306_1529'),
    ]

    operations = [
        migrations.AddField(
            model_name='argumentpost',
            name='attacking',
            field=models.ForeignKey(default=43, on_delete=models.SET(0), related_name='attackings', to='arguments.ArgumentPost'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='argumentpost',
            name='parent',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='parents', to='arguments.ArgumentPost'),
        ),
    ]
