# Generated by Django 3.0.2 on 2020-03-06 18:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('arguments', '0019_auto_20200306_1836'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='argumentpost',
            name='attacking',
        ),
        migrations.RemoveField(
            model_name='argumentpost',
            name='parent',
        ),
    ]
