# Generated by Django 3.0.2 on 2020-03-06 18:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('arguments', '0020_auto_20200306_1838'),
    ]

    operations = [
        migrations.AddField(
            model_name='argumentpost',
            name='attacking',
            field=models.ForeignKey(default=30, on_delete=models.SET(1), related_name='attackings', to='arguments.ArgumentPost'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='argumentpost',
            name='parent',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='parents', to='arguments.ArgumentPost'),
        ),
    ]
