# Generated by Django 3.0.2 on 2020-03-06 18:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('arguments', '0021_auto_20200306_1848'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='argumentpost',
            name='attacking',
        ),
    ]
