# Generated by Django 3.0.2 on 2020-03-06 18:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('arguments', '0022_remove_argumentpost_attacking'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='argumentpost',
            name='parent',
        ),
    ]
