# Generated by Django 3.0.2 on 2020-03-06 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('arguments', '0023_remove_argumentpost_parent'),
    ]

    operations = [
        migrations.AddField(
            model_name='argumentpost',
            name='attacking',
            field=models.TextField(blank=True, null=True),
        ),
    ]
