# Generated by Django 3.0.2 on 2020-03-06 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('arguments', '0024_argumentpost_attacking'),
    ]

    operations = [
        migrations.AlterField(
            model_name='argumentpost',
            name='attacking',
            field=models.TextField(blank=True, default='aa', null=True),
        ),
    ]
