# Generated by Django 3.0.2 on 2020-03-06 19:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('arguments', '0025_auto_20200306_1858'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='argumentpost',
            name='attacking',
        ),
        migrations.AddField(
            model_name='argumentpost',
            name='parent',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='parents', to='arguments.ArgumentPost'),
        ),
    ]
