# Generated by Django 3.0.2 on 2020-03-06 19:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('arguments', '0026_auto_20200306_1900'),
    ]

    operations = [
        migrations.AddField(
            model_name='argumentpost',
            name='attacking',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='attackings', to='arguments.ArgumentPost'),
        ),
    ]
