# Generated by Django 3.0.2 on 2020-03-06 19:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('arguments', '0027_argumentpost_attacking'),
    ]

    operations = [
        migrations.AddField(
            model_name='argumentpost',
            name='root_argument',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rootarg', to='arguments.ArgumentPost'),
        ),
    ]
